# Generated by Django 3.1.4 on 2021-01-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210101_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='pic',
        ),
        migrations.AddField(
            model_name='news',
            name='picname',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='news',
            name='picurl',
            field=models.TextField(default='-'),
        ),
    ]
