# Generated by Django 3.1.4 on 2021-06-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0002_blacklist_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='date',
        ),
    ]
