# Generated by Django 3.1.4 on 2021-01-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcat',
            name='catid',
            field=models.IntegerField(default=0),
        ),
    ]
